storage:
  output_dir: "output_results"
  temp_dir: "output_results/temp"
  log_file: "logs/app.log"
  auto_fetch_dir: "test_videos/landscape"

models:
  depth:
    model_name: "depth-anything/Depth-Anything-V2-Base-hf"
  layer_separation:
    device: "cuda"      # or cpu 
    sampling_step: 10

    sam2:
      checkpoint: "processors/layer_separation/checkpoints/sam2_hiera_small.pt"
      model_cfg: "sam2_hiera_s.yaml"
      chunk_size: 150

    cotracker:
      checkpoint: "processors/layer_separation/checkpoints/scaled_offline.pth"
      chunk_size: 60
      grid_step: 12

    nanotrack:
      backbone: "processors/layer_separation/checkpoints/nanotrack_backbone_sim.onnx"
      head: "processors/layer_separation/checkpoints/nanotrack_head_sim.onnx"

    xmem:
      checkpoint: "processors/layer_separation/checkpoints/XMem-s012.pth"
